---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: floo-proxy-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: floo-proxy-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: floo-proxy-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: floo-proxy-role
subjects:
- kind: ServiceAccount
  name: floo-proxy-service-account
  namespace: default